name: build

on: [push]

env:
  DOTNET_VERSION: '7.0.x' # The .NET SDK version to use

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    # needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: |
            cd src
            dotnet restore
        
      - name: Run tests
        run: |
            cd src
            dotnet test
